---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12.3
  - biopython
  - numpy
  - pandas
  - gtfparse=2.5.0