---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::gffread=0.12.7
  - bioconda::orfanage=1.2.0
  - conda-forge::polars=0.20.31