---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::pbpigeon=1.3.0 
  - bioconda::gffread=0.12.7
  - conda-forge::polars=0.20.31
  - conda-forge::pyarrow=16.1.0
  - conda-forge::pandas=2.2.2
  